updates:
- directory: /
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- directory: /
  labels:
  - 'type: dependencies'
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: daily
- directory: /
  package-ecosystem: github-actions
  schedule:
    interval: daily
version: 2
